In [ ]:
import pandas as pd
df=pd.read_csv('Election.csv')
df.head()

#READ THE CSV FILE AND FIND DF.SHAPE, DF.DESCRIBE().

df.shape


# (2263, 19)


df.describe()

#CHECK THE NULL VALUES FROM THE DATASET.

df.isnull().sum()

'''
STATE                                          0
CONSTITUENCY                                   0
NAME                                           0
WINNER                                         0
PARTY                                          0
SYMBOL                                       245
GENDER                                       245
CRIMINAL\nCASES                              245
AGE                                          245
CATEGORY                                     245
EDUCATION                                    245
ASSETS                                       245
LIABILITIES                                  245
GENERAL\nVOTES                                 0
POSTAL\nVOTES                                  0
TOTAL\nVOTES                                   0
OVER TOTAL ELECTORS \nIN CONSTITUENCY          0
OVER TOTAL VOTES POLLED \nIN CONSTITUENCY      0
TOTAL ELECTORS                                 0
dtype: int64
'''

# FILL THE NULL VALUES USING MEDIAN AND MODE.

df['SYMBOL']=df['SYMBOL'].fillna(df['SYMBOL'].mode()[0])
df['GENDER']=df['GENDER'].fillna(df['GENDER'].mode()[0])
df['CRIMINAL\nCASES']=df['CRIMINAL\nCASES'].fillna(df['CRIMINAL\nCASES'].mode()[0])
df['AGE']=df['AGE'].fillna(df['AGE'].median())
df['CATEGORY']=df['CATEGORY'].fillna(df['CATEGORY'].mode()[0])
df['EDUCATION']=df['EDUCATION'].fillna(df['EDUCATION'].mode()[0])
df['ASSETS']=df['ASSETS'].fillna(df['ASSETS'].mode()[0])
df['LIABILITIES']=df['LIABILITIES'].fillna(df['LIABILITIES'].mode()[0])


df.isnull().sum()

'''
STATE                                        0
CONSTITUENCY                                 0
NAME                                         0
WINNER                                       0
PARTY                                        0
SYMBOL                                       0
GENDER                                       0
CRIMINAL\nCASES                              0
AGE                                          0
CATEGORY                                     0
EDUCATION                                    0
ASSETS                                       0
LIABILITIES                                  0
GENERAL\nVOTES                               0
POSTAL\nVOTES                                0
TOTAL\nVOTES                                 0
OVER TOTAL ELECTORS \nIN CONSTITUENCY        0
OVER TOTAL VOTES POLLED \nIN CONSTITUENCY    0
TOTAL ELECTORS                               0
dtype: int64
'''
# REMOVE THE INSIGNIFICANT COLUMNS FROM THE DATASET IF NECESSARY.

df=df.drop(['CATEGORY', 'EDUCATION','ASSETS','LIABILITIES'],axis=1)

'''
STATE	CONSTITUENCY	NAME	WINNER	PARTY	SYMBOL	GENDER	CRIMINAL\nCASES	AGE	GENERAL\nVOTES	POSTAL\nVOTES	TOTAL\nVOTES	OVER TOTAL ELECTORS \nIN CONSTITUENCY	OVER TOTAL VOTES POLLED \nIN CONSTITUENCY	TOTAL ELECTORS
0	Telangana	ADILABAD	SOYAM BAPU RAO	1	BJP	Lotus	MALE	52	52.0	376892	482	377374	25.330684	35.468248	1489790
1	Telangana	ADILABAD	Godam Nagesh	0	TRS	Car	MALE	0	54.0	318665	149	318814	21.399929	29.964370	1489790
2	Telangana	ADILABAD	RATHOD RAMESH	0	INC	Hand	MALE	3	52.0	314057	181	314238	21.092771	29.534285	1489790
3	Telangana	ADILABAD	NOTA	0	NOTA	Lotus	MALE	0	52.0	13030	6	13036	0.875023	1.225214	1489790
4	Uttar Pradesh	AGRA	Satyapal Singh Baghel	1	BJP	Lotus	MALE	5	58.0	644459	2416	646875	33.383823	56.464615	1937690
'''


df.head()


df.shape

#(2263, 15)

# CONVERT THE CATEGORICAL COLUMNS TO NUMERICAL COLUMNS.

from sklearn.preprocessing import LabelEncoder
cat_num=['STATE','CONSTITUENCY','NAME','PARTY','SYMBOL','GENDER','CRIMINAL\nCASES']
le=LabelEncoder()
for i in cat_num:
    df[i]=le.fit_transform(df[i])

df.head()

# FIND THE STATISTICAL INFORMATION OF THE DATASET.

import numpy as np
mean=np.mean(df)
mean

'''
STATE                                        2.012903e+01
CONSTITUENCY                                 2.732090e+02
NAME                                         1.027752e+03
WINNER                                       2.381794e-01
PARTY                                        5.319841e+01
SYMBOL                                       6.294344e+01
GENDER                                       8.859920e-01
CRIMINAL\nCASES                              3.505966e+00
AGE                                          5.224392e+01
GENERAL\nVOTES                               2.615991e+05
POSTAL\nVOTES                                9.907106e+02
TOTAL\nVOTES                                 2.625898e+05
OVER TOTAL ELECTORS \nIN CONSTITUENCY        1.581141e+01
OVER TOTAL VOTES POLLED \nIN CONSTITUENCY    2.319053e+01
TOTAL ELECTORS                               1.658016e+06
dtype: float64
'''


median=np.median(df)
median


# 49.0

print(np.std(df))

'''
STATE                                            11.454772
CONSTITUENCY                                    157.505746
NAME                                            552.914500
WINNER                                            0.425969
PARTY                                            30.042847
SYMBOL                                           25.134361
GENDER                                            0.317821
CRIMINAL\nCASES                                   7.217463
AGE                                              11.206008
GENERAL\nVOTES                               254934.242775
POSTAL\nVOTES                                  1602.484994
TOTAL\nVOTES                                 255925.671234
OVER TOTAL ELECTORS \nIN CONSTITUENCY            14.959555
OVER TOTAL VOTES POLLED \nIN CONSTITUENCY        21.559993
TOTAL ELECTORS                               314449.173953
dtype: float64
'''


print(np.percentile(df,90))


# 79614.8000000001

# PERFORM EDA ON THE DATASET USING VISUALIZATION SUCH AS BAR PLOT, BOX PLOT, COUNT PLOT ETC.

import seaborn as sns
sns.barplot(x='STATE',y='WINNER',data=df);


sns.boxplot(x='STATE',y='WINNER',data=df);



sns.countplot(x='WINNER',data=df);



sns.violinplot(x="STATE", y="WINNER", data=df, size=8)

# APPLY STANDARD SCALING RO STANDARDIZE THE DATA.

from sklearn.preprocessing import StandardScaler
trans = StandardScaler()

dataset = pd.DataFrame(df)
dataset=trans.fit_transform(dataset.to_numpy())
dataset

'''
array([[ 0.94903394, -1.73459712,  1.23933871, ...,  0.63633392,
         0.56946784, -0.53498613],
       [ 0.94903394, -1.73459712, -0.59277096, ...,  0.37357508,
         0.31418583, -0.53498613],
       [ 0.94903394, -1.73459712,  0.85049016, ...,  0.35304255,
         0.29423756, -0.53498613],
       ...,
       [ 0.94903394,  1.68115127, -0.05380878, ...,  0.85218582,
         0.82501408, -0.50675899],
       [ 0.94903394,  1.68115127, -1.40844861, ..., -0.43718102,
        -0.45862018, -0.50675899],
       [ 0.94903394,  1.68115127,  0.31695378, ..., -1.00725488,
        -1.02615946, -0.50675899]])
'''

df.describe()

# SPLIT THE DATA INTO TRAINING AND TESTING.

from sklearn.model_selection import train_test_split
X = df.drop(["WINNER"],axis = 1)
y = df['WINNER']

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=156)

# APPLY LOGISTIC REGRESSION.

from sklearn.linear_model import LogisticRegression
my_model = LogisticRegression()


result = my_model.fit(X_train, y_train)

predictions = result.predict(X_test)
predictions

'''
array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0], dtype=int64)
'''

from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)


# 0.9139072847682119


from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns
get_ipython().run_line_magic('matplotlib', 'inline')


confusion_mat = confusion_matrix(y_test, predictions)


confusion_df = pd.DataFrame(confusion_mat, index=['Actual neg','Actual pos'], columns=['Predicted neg','Predicted pos'])



confusion_df

'''
	Predicted neg	Predicted pos
Actual neg	336	24
Actual pos	15	78
'''


Color_conf_matrix = sns.heatmap(confusion_df, cmap='coolwarm',annot = True)

from sklearn.metrics import classification_report
matrix = classification_report(y_test,predictions,labels=[1,0])
matrix

'''
'              precision    recall  f1-score   support\n\n           1       0.76      0.84      0.80        93\n           0       0.96      0.93      0.95       360\n\n    accuracy                           0.91       453\n   macro avg       0.86      0.89      0.87       453\nweighted avg       0.92      0.91      0.92       453\n'
'''


pred_new=my_model.predict([[4,17.9,35.2,0,12,12.3,11,48,1,12,6,20,20,13]])
pred_new


# array([0], dtype=int64)


# APPLY DECISION TREE.

from sklearn.tree import DecisionTreeClassifier
my_model = DecisionTreeClassifier(random_state=0)
result = my_model.fit(X_train,y_train)


predictions = result.predict(X_test)
predictions

'''
array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1], dtype=int64)
'''


accuracy_score(y_test,predictions)


# 0.9359823399558499


from sklearn.metrics import classification_report
matrix = classification_report(y_test,predictions,labels=[1,0])
matrix

'''
'              precision    recall  f1-score   support\n\n           1       0.85      0.84      0.84        93\n           0       0.96      0.96      0.96       360\n\n    accuracy                           0.94       453\n   macro avg       0.90      0.90      0.90       453\nweighted avg       0.94      0.94      0.94       453\n'
'''


from sklearn.metrics import confusion_matrix
import seaborn as sn
matrix=confusion_matrix(y_test,predictions)
print(matrix)

'''
[[346  14]
 [ 15  78]]
'''


pred_new=my_model.predict([[4,17.9,35.2,0,12,12.3,11,48,1,12,6,20,20,13]])
pred_new


# array([0], dtype=int64)

# APPLY RANDOM FOREST.


from sklearn.ensemble import RandomForestClassifier
my_model = RandomForestClassifier(n_estimators = 50, criterion = 'entropy', random_state = 42)
result=my_model.fit(X_train, y_train)


predictions = result.predict(X_test)
predictions


'''
array([0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1], dtype=int64)
'''


from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, predictions))


# Accuracy: 0.9624724061810155


import seaborn as sn
from sklearn.metrics import confusion_matrix
conf_matrix =confusion_matrix(predictions,y_test)
confusion_df = pd.DataFrame(conf_matrix, index=['Actual 0','Actual 1'], columns=['Predicted 0','Predicted 1'])
confusion_df

'''

Predicted 0	Predicted 1
Actual 0	355	12
Actual 1	5	81
'''


from sklearn.metrics import classification_report
matrix = classification_report(y_test,predictions,labels=[1,0])
matrix

'''
'              precision    recall  f1-score   support\n\n           1       0.94      0.87      0.91        93\n           0       0.97      0.99      0.98       360\n\n    accuracy                           0.96       453\n   macro avg       0.95      0.93      0.94       453\nweighted avg       0.96      0.96      0.96       453\n'
'''


pred_new=my_model.predict([[4,17.9,35.2,0,12,12.3,11,48,1,12,6,20,20,13]])
pred_new


# Iarray([0], dtype=int64)

# APPLY KNN.

from sklearn.neighbors import KNeighborsClassifier
my_model = KNeighborsClassifier(n_neighbors=1)
result = my_model.fit(X_train,y_train)


predictions = result.predict(X_test)

from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, predictions))


# Accuracy: 0.9006622516556292


from sklearn.metrics import classification_report,confusion_matrix
confusion_matrix(y_test,predictions)

'''
array([[338,  22],
       [ 23,  70]], dtype=int64)
'''


matrix = classification_report(y_test,predictions,labels=[1,0])
matrix

'''
'              precision    recall  f1-score   support\n\n           1       0.76      0.75      0.76        93\n           0       0.94      0.94      0.94       360\n\n    accuracy                           0.90       453\n   macro avg       0.85      0.85      0.85       453\nweighted avg       0.90      0.90      0.90       453\n'
'''


pred_new=my_model.predict([[4,17.9,35.2,0,12,12.3,11,48,1,12,6,20,20,13]])
pred_new


# APPLY SVM.

from sklearn.svm import SVC
my_model = SVC(kernel = 'rbf', random_state = 0)
result = my_model.fit(X_train, y_train)



predictions = result.predict(X_test)
predictions

'''
array([0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0], dtype=int64)
'''


from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, predictions))


# Accuracy: 0.9183222958057395


import seaborn as sn
from sklearn.metrics import confusion_matrix
conf_matrix =confusion_matrix(predictions,y_test)
confusion_df = pd.DataFrame(conf_matrix, index=['Actual 0','Actual 1'], columns=['Predicted 0','Predicted 1'])
confusion_df

'''

Predicted 0	Predicted 1
Actual 0	340	17
Actual 1	20	76
'''


matrix = classification_report(y_test,predictions,labels=[1,0])
matrix

'''
'              precision    recall  f1-score   support\n\n           1       0.79      0.82      0.80        93\n           0       0.95      0.94      0.95       360\n\n    accuracy                           0.92       453\n   macro avg       0.87      0.88      0.88       453\nweighted avg       0.92      0.92      0.92       453\n'
'''


pred_new=my_model.predict([[4,17.9,35.2,0,12,12.3,11,48,1,12,6,20,20,13]])
pred_new

# array([0], dtype=int64)




